/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAparelhosIndexRouteImport } from './routes/_authenticated/aparelhos.index'
import { Route as AuthenticatedAparelhosNovoRouteImport } from './routes/_authenticated/aparelhos.novo'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos.index'
import { Route as AuthenticatedOsIndexRouteImport } from './routes/_authenticated/os.index'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated/os.$id'
import { Route as AuthenticatedOsNovoRouteImport } from './routes/_authenticated/os.novo'
import { Route as AuthenticatedClientesIdEditarRouteImport } from './routes/_authenticated/clientes.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAparelhosIndexRoute =
  AuthenticatedAparelhosIndexRouteImport.update({
    id: '/aparelhos/',
    path: '/aparelhos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAparelhosNovoRoute =
  AuthenticatedAparelhosNovoRouteImport.update({
    id: '/aparelhos/novo',
    path: '/aparelhos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOsIndexRoute = AuthenticatedOsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/os/$id',
  path: '/os/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsNovoRoute = AuthenticatedOsNovoRouteImport.update({
  id: '/os/novo',
  path: '/os/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIdEditarRoute =
  AuthenticatedClientesIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/aparelhos/novo': typeof AuthenticatedAparelhosNovoRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os/novo': typeof AuthenticatedOsNovoRoute
  '/aparelhos/': typeof AuthenticatedAparelhosIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/os/': typeof AuthenticatedOsIndexRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/aparelhos/novo': typeof AuthenticatedAparelhosNovoRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/os/novo': typeof AuthenticatedOsNovoRoute
  '/aparelhos': typeof AuthenticatedAparelhosIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/os': typeof AuthenticatedOsIndexRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/aparelhos/novo': typeof AuthenticatedAparelhosNovoRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
  '/_authenticated/os/novo': typeof AuthenticatedOsNovoRoute
  '/_authenticated/aparelhos/': typeof AuthenticatedAparelhosIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/os/': typeof AuthenticatedOsIndexRoute
  '/_authenticated/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/aparelhos/novo'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/os/$id'
    | '/os/novo'
    | '/aparelhos/'
    | '/clientes/'
    | '/orcamentos/'
    | '/os/'
    | '/clientes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/aparelhos/novo'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/os/$id'
    | '/os/novo'
    | '/aparelhos'
    | '/clientes'
    | '/orcamentos'
    | '/os'
    | '/clientes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/aparelhos/novo'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/os/$id'
    | '/_authenticated/os/novo'
    | '/_authenticated/aparelhos/'
    | '/_authenticated/clientes/'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/os/'
    | '/_authenticated/clientes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aparelhos/': {
      id: '/_authenticated/aparelhos/'
      path: '/aparelhos'
      fullPath: '/aparelhos/'
      preLoaderRoute: typeof AuthenticatedAparelhosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aparelhos/novo': {
      id: '/_authenticated/aparelhos/novo'
      path: '/aparelhos/novo'
      fullPath: '/aparelhos/novo'
      preLoaderRoute: typeof AuthenticatedAparelhosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/': {
      id: '/_authenticated/os/'
      path: '/os'
      fullPath: '/os/'
      preLoaderRoute: typeof AuthenticatedOsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/os/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/novo': {
      id: '/_authenticated/os/novo'
      path: '/os/novo'
      fullPath: '/os/novo'
      preLoaderRoute: typeof AuthenticatedOsNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id/editar': {
      id: '/_authenticated/clientes/$id/editar'
      path: '/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AuthenticatedClientesIdEditarRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
  }
}

interface AuthenticatedClientesIdRouteChildren {
  AuthenticatedClientesIdEditarRoute: typeof AuthenticatedClientesIdEditarRoute
}

const AuthenticatedClientesIdRouteChildren: AuthenticatedClientesIdRouteChildren =
  {
    AuthenticatedClientesIdEditarRoute: AuthenticatedClientesIdEditarRoute,
  }

const AuthenticatedClientesIdRouteWithChildren =
  AuthenticatedClientesIdRoute._addFileChildren(
    AuthenticatedClientesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAparelhosNovoRoute: typeof AuthenticatedAparelhosNovoRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRouteWithChildren
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
  AuthenticatedOsNovoRoute: typeof AuthenticatedOsNovoRoute
  AuthenticatedAparelhosIndexRoute: typeof AuthenticatedAparelhosIndexRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedOsIndexRoute: typeof AuthenticatedOsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAparelhosNovoRoute: AuthenticatedAparelhosNovoRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRouteWithChildren,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedOsIdRoute: AuthenticatedOsIdRoute,
  AuthenticatedOsNovoRoute: AuthenticatedOsNovoRoute,
  AuthenticatedAparelhosIndexRoute: AuthenticatedAparelhosIndexRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
  AuthenticatedOsIndexRoute: AuthenticatedOsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
